# Generated by Django 3.0.2 on 2020-06-17 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams',
            name='examanswer',
            field=models.TextField(blank=True, max_length=50000),
        ),
        migrations.AlterField(
            model_name='exams',
            name='examanswer1',
            field=models.TextField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='exams',
            name='examanswer2',
            field=models.TextField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='exams',
            name='examanswer3',
            field=models.TextField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='exams',
            name='examanswer4',
            field=models.TextField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='exams',
            name='examlinkaudio',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='exams',
            name='examlinkpic',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='exams',
            name='examlinkvideo',
            field=models.TextField(blank=True, max_length=2000),
        ),
        migrations.AlterField(
            model_name='exams',
            name='examquestion',
            field=models.TextField(max_length=50000),
        ),
        migrations.AlterField(
            model_name='exams',
            name='examtext',
            field=models.TextField(blank=True, max_length=50000),
        ),
    ]
