# Generated by Django 3.0.2 on 2020-06-17 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0002_auto_20200617_1353'),
    ]

    operations = [
        migrations.AddField(
            model_name='exams',
            name='examanswer1_true',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exams',
            name='examanswer2_true',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exams',
            name='examanswer3_true',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='exams',
            name='examanswer4_true',
            field=models.BooleanField(default=True),
        ),
    ]
