# Generated by Django 3.0.2 on 2020-06-18 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('exam', '0005_auto_20200618_1334'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAnswerTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userexamanswer', models.IntegerField()),
                ('courseexamfkey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam.courseexam2')),
                ('examquestionfkey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam.exams')),
                ('usernamefkey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
