# Generated by Django 3.0.2 on 2020-06-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0006_useranswertest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswertest',
            name='courseexamfkey',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='useranswertest',
            name='examquestionfkey',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='useranswertest',
            name='usernamefkey',
            field=models.IntegerField(),
        ),
    ]
