# Generated by Django 3.0.2 on 2020-07-04 17:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0008_auto_20200704_2205'),
    ]

    operations = [
        migrations.CreateModel(
            name='exams2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examquestion_published', models.BooleanField(default=True)),
                ('examquestion', models.TextField(max_length=50000)),
                ('examanswer1', models.TextField(max_length=50001)),
                ('examanswer2', models.TextField(max_length=50000)),
                ('examanswer3', models.TextField(max_length=50000)),
                ('examanswer4', models.TextField(max_length=50000)),
                ('trueanswer', models.TextField(max_length=1)),
                ('examtext_published', models.BooleanField(default=False)),
                ('examtext', models.TextField(blank=True, max_length=50000)),
                ('examfiletext_published', models.BooleanField(default=False)),
                ('examfiletext', models.FileField(blank=True, upload_to='courseexam/exams/%y/%m/%d/')),
                ('examlinkpic_published', models.BooleanField(default=False)),
                ('examlinkpic', models.TextField(blank=True, max_length=2000)),
                ('examfilepic_published', models.BooleanField(default=False)),
                ('examfilepic', models.FileField(blank=True, upload_to='courseexam/exams/%y/%m/%d/')),
                ('examlinkvideo_published', models.BooleanField(default=False)),
                ('examlinkvideo', models.TextField(blank=True, max_length=2000)),
                ('examfilevideo_published', models.BooleanField(default=False)),
                ('examfilevideo', models.FileField(blank=True, upload_to='courseexam/exams/%y/%m/%d/')),
                ('examlinkaudio_published', models.BooleanField(default=False)),
                ('examlinkaudio', models.TextField(blank=True, max_length=2000)),
                ('examfileaudio_published', models.BooleanField(default=False)),
                ('examfileaudio', models.FileField(blank=True, upload_to='courseexam/exams/%y/%m/%d/')),
                ('examanswer_published', models.BooleanField(default=False)),
                ('examanswer', models.TextField(blank=True, max_length=50000)),
                ('examfileanswer_published', models.BooleanField(default=False)),
                ('examfileanswer', models.FileField(blank=True, upload_to='courseexam/exams/%y/%m/%d/')),
                ('coursenamefkey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam.courseexam2')),
            ],
        ),
    ]
