# Generated by Django 3.0.2 on 2020-07-07 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0009_exams2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exams2',
            name='trueanswer',
            field=models.IntegerField(max_length=1),
        ),
    ]
