# Generated by Django 3.0.2 on 2020-07-13 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200713_1241'),
        ('exam', '0010_auto_20200707_2023'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='courseexam2',
            options={'verbose_name_plural': 'ثبت آزمون'},
        ),
        migrations.AlterModelOptions(
            name='exams2',
            options={'verbose_name_plural': 'ثبت سوالات آزمون'},
        ),
        migrations.AlterModelOptions(
            name='tutorialexamadmin',
            options={'verbose_name_plural': 'تنظیمات صفحه آزمون'},
        ),
        migrations.AlterModelOptions(
            name='useranswertest',
            options={'verbose_name_plural': 'جواب کاربر به سوال'},
        ),
        migrations.AlterField(
            model_name='courseexam2',
            name='coursename',
            field=models.CharField(max_length=1000, verbose_name='نام آزمون'),
        ),
        migrations.AlterField(
            model_name='courseexam2',
            name='hazine',
            field=models.IntegerField(verbose_name='هزینه به ریال'),
        ),
        migrations.AlterField(
            model_name='courseexam2',
            name='maghtafkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.maghtaTahsili', verbose_name='انتخاب مقطع تحصیلی'),
        ),
        migrations.AlterField(
            model_name='courseexam2',
            name='modaresinfkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.modaresin', verbose_name='انتخاب مدرس'),
        ),
        migrations.AlterField(
            model_name='courseexam2',
            name='pic',
            field=models.ImageField(upload_to='courseexam/photos/%y/%m/%d/', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='courseexam2',
            name='reshteTahsilifkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.reshteTahsili', verbose_name='انتخاب رشته تحصیلی'),
        ),
        migrations.AlterField(
            model_name='courseexam2',
            name='saattadris',
            field=models.CharField(max_length=1000, verbose_name='مدت آزمون به دقیقه'),
        ),
        migrations.AlterField(
            model_name='courseexam2',
            name='tozihat',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='exams',
            name='coursenamefkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam.courseexam2', verbose_name='انتخاب آزمون'),
        ),
        migrations.AlterField(
            model_name='exams',
            name='examquestion',
            field=models.TextField(max_length=50000, verbose_name='متن سوال'),
        ),
        migrations.AlterField(
            model_name='exams',
            name='examquestion_published',
            field=models.BooleanField(default=True, verbose_name='نمایش یا عدم نمایش سوال'),
        ),
        migrations.AlterField(
            model_name='exams2',
            name='coursenamefkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam.courseexam2', verbose_name='انتخاب آزمون'),
        ),
        migrations.AlterField(
            model_name='exams2',
            name='examanswer',
            field=models.TextField(blank=True, max_length=50000, verbose_name='متن جواب برای سوال'),
        ),
        migrations.AlterField(
            model_name='exams2',
            name='examanswer1',
            field=models.TextField(max_length=50001, verbose_name='گزینه 1'),
        ),
        migrations.AlterField(
            model_name='exams2',
            name='examanswer2',
            field=models.TextField(max_length=50000, verbose_name='گزینه 2'),
        ),
        migrations.AlterField(
            model_name='exams2',
            name='examanswer3',
            field=models.TextField(max_length=50000, verbose_name='گزینه 3'),
        ),
        migrations.AlterField(
            model_name='exams2',
            name='examanswer4',
            field=models.TextField(max_length=50000, verbose_name='گزینه 4'),
        ),
        migrations.AlterField(
            model_name='exams2',
            name='examanswer_published',
            field=models.BooleanField(default=False, verbose_name='نمایش یا عدم نمایش متن جواب سوال'),
        ),
        migrations.AlterField(
            model_name='exams2',
            name='examfileanswer',
            field=models.FileField(blank=True, upload_to='courseexam/exams/%y/%m/%d/', verbose_name='فایل متن توضیحات برای سوال'),
        ),
        migrations.AlterField(
            model_name='exams2',
            name='examfileanswer_published',
            field=models.BooleanField(default=False, verbose_name='نمایش یا عدم نمایش فایل جواب سوال'),
        ),
        migrations.AlterField(
            model_name='exams2',
            name='examfileaudio',
            field=models.FileField(blank=True, upload_to='courseexam/exams/%y/%m/%d/', verbose_name='فایل صوت توضیحات برای سوال'),
        ),
        migrations.AlterField(
            model_name='exams2',
            name='examfileaudio_published',
            field=models.BooleanField(default=False, verbose_name='نمایش یا عدم نمایش فایل صوت برای سوال'),
        ),
        migrations.AlterField(
            model_name='exams2',
            name='examfilepic',
            field=models.FileField(blank=True, upload_to='courseexam/exams/%y/%m/%d/', verbose_name='فایل عکس توضیحات برای سوال'),
        ),
        migrations.AlterField(
            model_name='exams2',
            name='examfilepic_published',
            field=models.BooleanField(default=False, verbose_name='نمایش یا عدم نمایش فایل عکس برای سوال'),
        ),
        migrations.AlterField(
            model_name='exams2',
            name='examfiletext',
            field=models.FileField(blank=True, upload_to='courseexam/exams/%y/%m/%d/', verbose_name='فایل متن توضیحات برای سوال'),
        ),
        migrations.AlterField(
            model_name='exams2',
            name='examfiletext_published',
            field=models.BooleanField(default=False, verbose_name='نمایش یا عدم نمایش فایل متن برای سوال'),
        ),
        migrations.AlterField(
            model_name='exams2',
            name='examfilevideo',
            field=models.FileField(blank=True, upload_to='courseexam/exams/%y/%m/%d/', verbose_name='فایل ویدئو توضیحات برای سوال'),
        ),
        migrations.AlterField(
            model_name='exams2',
            name='examfilevideo_published',
            field=models.BooleanField(default=False, verbose_name='نمایش یا عدم نمایش فایل ویدئو برای سوال'),
        ),
        migrations.AlterField(
            model_name='exams2',
            name='examlinkaudio',
            field=models.TextField(blank=True, max_length=2000, verbose_name='لینک صوت توضیحات برای سوال'),
        ),
        migrations.AlterField(
            model_name='exams2',
            name='examlinkaudio_published',
            field=models.BooleanField(default=False, verbose_name='نمایش یا عدم نمایش لینک صوت برای سوال'),
        ),
        migrations.AlterField(
            model_name='exams2',
            name='examlinkpic',
            field=models.TextField(blank=True, max_length=2000, verbose_name='لینک عکس توضیحات برای سوال'),
        ),
        migrations.AlterField(
            model_name='exams2',
            name='examlinkpic_published',
            field=models.BooleanField(default=False, verbose_name='نمایش یا عدم نمایش لینک عکس برای سوال'),
        ),
        migrations.AlterField(
            model_name='exams2',
            name='examlinkvideo',
            field=models.TextField(blank=True, max_length=2000, verbose_name='لینک ویدئو توضیحات برای سوال'),
        ),
        migrations.AlterField(
            model_name='exams2',
            name='examlinkvideo_published',
            field=models.BooleanField(default=False, verbose_name='نمایش یا عدم نمایش لینک ویدئو برای سوال'),
        ),
        migrations.AlterField(
            model_name='exams2',
            name='examquestion',
            field=models.TextField(max_length=50000, verbose_name='متن سوال'),
        ),
        migrations.AlterField(
            model_name='exams2',
            name='examquestion_published',
            field=models.BooleanField(default=True, verbose_name='نمایش یا عدم نمایش سوال'),
        ),
        migrations.AlterField(
            model_name='exams2',
            name='examtext',
            field=models.TextField(blank=True, max_length=50000, verbose_name='متن توضیحات برای سوال'),
        ),
        migrations.AlterField(
            model_name='exams2',
            name='examtext_published',
            field=models.BooleanField(default=False, verbose_name='نمایش یا عدم نمایش متن برای سوال'),
        ),
        migrations.AlterField(
            model_name='exams2',
            name='trueanswer',
            field=models.TextField(max_length=1, verbose_name='شماره گزینه صحیح از 1 تا 4'),
        ),
        migrations.AlterField(
            model_name='tutorialexamadmin',
            name='pic',
            field=models.ImageField(upload_to='tutorialexam/photos/%y/%m/%d/', verbose_name='عکسر بالای صفحه'),
        ),
        migrations.AlterField(
            model_name='tutorialexamadmin',
            name='text_click',
            field=models.CharField(max_length=500, verbose_name='تیتر کلیک سرچ'),
        ),
        migrations.AlterField(
            model_name='tutorialexamadmin',
            name='title_1',
            field=models.CharField(max_length=500, verbose_name='تیتر آزمون های مرتبط'),
        ),
        migrations.AlterField(
            model_name='tutorialexamadmin',
            name='title_2',
            field=models.CharField(max_length=500, verbose_name='تیتر جدیدترین آزمون ها'),
        ),
        migrations.AlterField(
            model_name='tutorialexamadmin',
            name='title_page',
            field=models.CharField(max_length=500, verbose_name='تیتر صفحه'),
        ),
        migrations.AlterField(
            model_name='tutorialexamadmin',
            name='title_search',
            field=models.CharField(max_length=500, verbose_name='تیتر سرچ'),
        ),
        migrations.AlterField(
            model_name='useranswertest',
            name='courseexamfkey',
            field=models.IntegerField(verbose_name='آیدی درس'),
        ),
        migrations.AlterField(
            model_name='useranswertest',
            name='examquestionfkey',
            field=models.IntegerField(verbose_name='آیدی سوال'),
        ),
        migrations.AlterField(
            model_name='useranswertest',
            name='userexamanswer',
            field=models.IntegerField(verbose_name='جواب کاربر'),
        ),
        migrations.AlterField(
            model_name='useranswertest',
            name='usernamefkey',
            field=models.IntegerField(verbose_name='آیدی کاربر'),
        ),
    ]
