# Generated by Django 3.0.2 on 2020-07-13 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0012_auto_20200713_1244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useranswertest',
            name='courseexamfkey',
            field=models.TextField(verbose_name='آیدی درس'),
        ),
        migrations.AlterField(
            model_name='useranswertest',
            name='examquestionfkey',
            field=models.TextField(verbose_name='آیدی سوال'),
        ),
        migrations.AlterField(
            model_name='useranswertest',
            name='userexamanswer',
            field=models.TextField(verbose_name='جواب کاربر'),
        ),
        migrations.AlterField(
            model_name='useranswertest',
            name='usernamefkey',
            field=models.TextField(verbose_name='آیدی کاربر'),
        ),
    ]
