# Generated by Django 3.0.2 on 2020-09-10 19:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0015_auto_20200910_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseexam2',
            name='tozihat',
            field=ckeditor.fields.RichTextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='exams',
            name='examquestion',
            field=ckeditor.fields.RichTextField(verbose_name='متن سوال'),
        ),
        migrations.AlterField(
            model_name='exams2',
            name='examquestion',
            field=ckeditor.fields.RichTextField(verbose_name='متن سوال'),
        ),
        migrations.AlterField(
            model_name='exams2',
            name='examtext',
            field=ckeditor.fields.RichTextField(verbose_name='متن توضیحات برای سوال'),
        ),
    ]
