# Generated by Django 3.0.2 on 2021-02-11 07:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0017_auto_20201111_2216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exams2',
            name='examanswer1',
        ),
        migrations.RemoveField(
            model_name='exams2',
            name='examanswer2',
        ),
        migrations.RemoveField(
            model_name='exams2',
            name='examanswer3',
        ),
        migrations.RemoveField(
            model_name='exams2',
            name='examanswer4',
        ),
        migrations.RemoveField(
            model_name='exams2',
            name='trueanswer',
        ),
        migrations.CreateModel(
            name='examsanswer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examanswer_number', models.IntegerField(verbose_name='نمره جواب سوال')),
                ('examanswer', models.TextField(max_length=50001, verbose_name='نمره جواب سوال')),
                ('coursenamefkey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam.exams2', verbose_name='انتخاب سوال')),
            ],
            options={
                'verbose_name_plural': 'ثبت جواب آزمون',
            },
        ),
    ]
