# Generated by Django 3.0.2 on 2021-02-11 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0019_auto_20210211_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courseexam2',
            name='maghtafkey',
        ),
        migrations.RemoveField(
            model_name='courseexam2',
            name='modaresinfkey',
        ),
        migrations.RemoveField(
            model_name='courseexam2',
            name='reshteTahsilifkey',
        ),
    ]
