# Generated by Django 3.0.2 on 2021-02-11 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0020_auto_20210211_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='examsanswer',
            name='coursequestionfkey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='exam.exams2', verbose_name='انتخاب سوال'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='examsanswer',
            name='coursenamefkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam.courseexam2', verbose_name='انتخاب آزمون'),
        ),
        migrations.AlterField(
            model_name='examsanswer',
            name='examanswer',
            field=models.TextField(max_length=50001, verbose_name='جواب سوال'),
        ),
    ]
