# Generated by Django 3.0.2 on 2021-02-20 15:52

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('exam', '0022_auto_20210211_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='examsanswer2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('examanswer_number', models.IntegerField(verbose_name='نمره جواب سوال')),
                ('examanswer', models.TextField(max_length=50001, verbose_name='جواب سوال')),
                ('coursenamefkey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='exam.courseexam2', verbose_name='انتخاب آزمون')),
                ('coursequestionfkey', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='coursenamefkey', chained_model_field='coursenamefkey', help_text='سوال را انتخاب کنید', on_delete=django.db.models.deletion.CASCADE, related_name='coursequestionfkey', to='exam.exams2')),
            ],
            options={
                'verbose_name_plural': 'ثبت جواب آزمون',
            },
        ),
        migrations.DeleteModel(
            name='examsanswer',
        ),
    ]
