# Generated by Django 3.0.2 on 2021-02-20 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20201023_1257'),
        ('exam', '0024_auto_20210220_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exams2',
            name='maghtafkey',
        ),
        migrations.RemoveField(
            model_name='exams2',
            name='modaresinfkey',
        ),
        migrations.RemoveField(
            model_name='exams2',
            name='reshteTahsilifkey',
        ),
        migrations.AddField(
            model_name='courseexam2',
            name='maghtafkey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.maghtaTahsili', verbose_name='مقطع'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseexam2',
            name='modaresinfkey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.modaresin', verbose_name='نام استاد'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='courseexam2',
            name='reshteTahsilifkey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.reshteTahsili', verbose_name='رشته'),
            preserve_default=False,
        ),
    ]
