# Generated by Django 3.0.2 on 2020-07-13 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200713_1241'),
        ('tutorialfile', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursefile2',
            options={'verbose_name_plural': 'درس ها'},
        ),
        migrations.AlterModelOptions(
            name='files',
            options={'verbose_name_plural': 'فایل ها'},
        ),
        migrations.AlterModelOptions(
            name='tutorialfileadmin',
            options={'verbose_name_plural': 'تنظیمات صفحه'},
        ),
        migrations.AlterField(
            model_name='coursefile2',
            name='coursename',
            field=models.CharField(max_length=1000, verbose_name='نام درس'),
        ),
        migrations.AlterField(
            model_name='coursefile2',
            name='hazine',
            field=models.IntegerField(verbose_name='هزینه به ریال'),
        ),
        migrations.AlterField(
            model_name='coursefile2',
            name='maghtafkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.maghtaTahsili', verbose_name='مقطع'),
        ),
        migrations.AlterField(
            model_name='coursefile2',
            name='modaresinfkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.modaresin', verbose_name='نام استاد'),
        ),
        migrations.AlterField(
            model_name='coursefile2',
            name='pic',
            field=models.ImageField(upload_to='coursefile/photos/%y/%m/%d/', verbose_name='فایل عکس'),
        ),
        migrations.AlterField(
            model_name='coursefile2',
            name='reshteTahsilifkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.reshteTahsili', verbose_name='رشته'),
        ),
        migrations.AlterField(
            model_name='coursefile2',
            name='saattadris',
            field=models.CharField(max_length=1000, verbose_name='زمان درس'),
        ),
        migrations.AlterField(
            model_name='coursefile2',
            name='tozihat',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='files',
            name='coursenamefkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tutorialfile.coursefile2', verbose_name='نام درس'),
        ),
        migrations.AlterField(
            model_name='files',
            name='filefile',
            field=models.FileField(blank=True, upload_to='coursefile/files/%y/%m/%d/', verbose_name='فایل'),
        ),
        migrations.AlterField(
            model_name='files',
            name='filefile_is_published',
            field=models.BooleanField(default=True, verbose_name='پابلیش فایل'),
        ),
        migrations.AlterField(
            model_name='files',
            name='filelink',
            field=models.CharField(blank=True, max_length=1000, verbose_name='لینک فایل'),
        ),
        migrations.AlterField(
            model_name='files',
            name='filelink_is_published',
            field=models.BooleanField(default=True, verbose_name='پابلیش لینک فایل'),
        ),
        migrations.AlterField(
            model_name='files',
            name='filename',
            field=models.CharField(max_length=1000, verbose_name='نام فایل'),
        ),
        migrations.AlterField(
            model_name='tutorialfileadmin',
            name='pic',
            field=models.ImageField(upload_to='tutorialfile/photos/%y/%m/%d/', verbose_name='عکس بالای صفحه'),
        ),
        migrations.AlterField(
            model_name='tutorialfileadmin',
            name='text_click',
            field=models.CharField(max_length=500, verbose_name='تیتر دکمه سرچ'),
        ),
        migrations.AlterField(
            model_name='tutorialfileadmin',
            name='title_1',
            field=models.CharField(max_length=500, verbose_name='تیتر اول، فایل های پیشنهادی'),
        ),
        migrations.AlterField(
            model_name='tutorialfileadmin',
            name='title_2',
            field=models.CharField(max_length=500, verbose_name='تیتر دوم، جدیدترین فایل ها'),
        ),
        migrations.AlterField(
            model_name='tutorialfileadmin',
            name='title_page',
            field=models.CharField(max_length=500, verbose_name='تیتر صفحه'),
        ),
        migrations.AlterField(
            model_name='tutorialfileadmin',
            name='title_search',
            field=models.CharField(max_length=500, verbose_name='تیتر قسمت سرچ'),
        ),
    ]
