# Generated by Django 3.0.2 on 2020-11-08 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialfile', '0004_auto_20200910_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='filepics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filepicname', models.CharField(max_length=1000, verbose_name='نام عکس')),
                ('filepiclink_is_published', models.BooleanField(default=True, verbose_name='پابلیش لینک عکس')),
                ('filepiclink', models.CharField(blank=True, max_length=1000, verbose_name='لینک عکس')),
                ('filepicfile_is_published', models.BooleanField(default=True, verbose_name='پابلیش فایل عکس')),
                ('filepicfile', models.FileField(blank=True, upload_to='coursefile/files/%y/%m/%d/', verbose_name='فایل عکس')),
                ('coursenamefkey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tutorialfile.coursefile2', verbose_name='نام درس')),
            ],
            options={
                'verbose_name_plural': 'عکس های محصول',
            },
        ),
    ]
