# Generated by Django 3.0.2 on 2020-08-29 10:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pages', '0008_auto_20200829_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='coursevoice2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='coursevoice/photos/%y/%m/%d/', verbose_name='فایل عکس')),
                ('coursename', models.CharField(max_length=1000, verbose_name='نام درس')),
                ('saattadris', models.CharField(max_length=1000, verbose_name='زمان درس')),
                ('tozihat', models.TextField(verbose_name='توضیحات')),
                ('hazine', models.IntegerField(verbose_name='هزینه به ریال')),
                ('maghtafkey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.maghtaTahsili', verbose_name='مقطع')),
                ('modaresinfkey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.modaresin', verbose_name='نام استاد')),
                ('reshteTahsilifkey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.reshteTahsili', verbose_name='رشته')),
            ],
            options={
                'verbose_name_plural': 'درس ها',
            },
        ),
        migrations.CreateModel(
            name='tutorialvoiceAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_page', models.CharField(max_length=500, verbose_name='تیتر صفحه')),
                ('pic', models.ImageField(upload_to='tutorialvoice/photos/%y/%m/%d/', verbose_name='عکس بالای صفحه')),
                ('title_search', models.CharField(max_length=500, verbose_name='تیتر قسمت سرچ')),
                ('text_click', models.CharField(max_length=500, verbose_name='تیتر دکمه سرچ')),
                ('title_1', models.CharField(max_length=500, verbose_name='تیتر اول، صوتهای پیشنهادی')),
                ('title_2', models.CharField(max_length=500, verbose_name='تیتر دوم، جدیدترین صوتها')),
            ],
            options={
                'verbose_name_plural': 'تنظیمات صفحه',
            },
        ),
        migrations.CreateModel(
            name='voices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voicename', models.CharField(max_length=1000, verbose_name='نام صوت')),
                ('voicelink_is_published', models.BooleanField(default=True, verbose_name='پابلیش لینک صوت')),
                ('voicelink', models.CharField(blank=True, max_length=1000, verbose_name='لینک صوت')),
                ('voicefile_is_published', models.BooleanField(default=True, verbose_name='پابلیش فایل صوت')),
                ('voicefile', models.FileField(blank=True, upload_to='coursevoice/voices/%y/%m/%d/', verbose_name='فایل صوت')),
                ('coursenamefkey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tutorialvoice.coursevoice2', verbose_name='نام درس')),
            ],
            options={
                'verbose_name_plural': 'صوت ها',
            },
        ),
    ]
