# Generated by Django 3.0.2 on 2020-09-10 16:32

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialvoice', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursevoice2',
            name='hazine',
            field=models.IntegerField(verbose_name='هزینه به تومان'),
        ),
        migrations.AlterField(
            model_name='coursevoice2',
            name='tozihat',
            field=ckeditor.fields.RichTextField(verbose_name='توضیحات'),
        ),
    ]
