# Generated by Django 3.0.2 on 2020-11-07 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialvoice', '0002_auto_20200910_2102'),
    ]

    operations = [
        migrations.CreateModel(
            name='voicepics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voicepicname', models.CharField(max_length=1000, verbose_name='نام عکس')),
                ('voicepiclink_is_published', models.BooleanField(default=True, verbose_name='پابلیش لینک عکس')),
                ('voicepiclink', models.CharField(blank=True, max_length=1000, verbose_name='لینک عکس')),
                ('voicepicfile_is_published', models.BooleanField(default=True, verbose_name='پابلیش فایل عکس')),
                ('voicepicfile', models.FileField(blank=True, upload_to='coursevoice/voices/%y/%m/%d/', verbose_name='فایل عکس')),
                ('coursenamefkey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tutorialvoice.coursevoice2', verbose_name='نام درس')),
            ],
            options={
                'verbose_name_plural': 'عکس های محصول',
            },
        ),
    ]
