# Generated by Django 3.0.2 on 2020-11-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialvoice', '0004_auto_20201111_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevoice2',
            name='size',
            field=models.CharField(default=1, max_length=1000, verbose_name='حجم فایل به مگابایت'),
            preserve_default=False,
        ),
    ]
