# Generated by Django 3.0.2 on 2020-08-11 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='galerys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=3000, verbose_name='تیتر عکس')),
                ('about', models.TextField(max_length=5000, verbose_name='توضیحات عکس')),
                ('pic', models.ImageField(upload_to='news/photos/%y/%m/%d/', verbose_name='عکس')),
            ],
            options={
                'verbose_name_plural': 'عکس ها',
            },
        ),
        migrations.CreateModel(
            name='galerysAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_page', models.CharField(max_length=500, verbose_name='تیتر صفحه')),
                ('pic', models.ImageField(upload_to='classlinks/photos/%y/%m/%d/', verbose_name='عکس بالای صفحه')),
                ('title_news', models.CharField(max_length=500, verbose_name='تیتر عکس های گالری')),
            ],
            options={
                'verbose_name_plural': 'تنظیمات صفحه گالری',
            },
        ),
    ]
