# Generated by Django 3.0.2 on 2020-06-02 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialbook', '0002_auto_20200602_1024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='bookbook_is_published',
            new_name='bookfile_is_published',
        ),
    ]
