# Generated by Django 3.0.2 on 2020-07-13 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200713_1241'),
        ('tutorialbook', '0003_auto_20200602_1118'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='books',
            options={'verbose_name_plural': 'کتاب ها'},
        ),
        migrations.AlterModelOptions(
            name='coursebook2',
            options={'verbose_name_plural': 'درس ها'},
        ),
        migrations.AlterModelOptions(
            name='tutorialbookadmin',
            options={'verbose_name_plural': 'تنظیمات صفحه'},
        ),
        migrations.AlterField(
            model_name='books',
            name='bookfile',
            field=models.FileField(blank=True, upload_to='coursebook/books/%y/%m/%d/', verbose_name='فایل کتاب'),
        ),
        migrations.AlterField(
            model_name='books',
            name='bookfile_is_published',
            field=models.BooleanField(default=True, verbose_name='پابلیش فایل کتاب'),
        ),
        migrations.AlterField(
            model_name='books',
            name='booklink',
            field=models.CharField(blank=True, max_length=1000, verbose_name='لینک فایل کتاب'),
        ),
        migrations.AlterField(
            model_name='books',
            name='booklink_is_published',
            field=models.BooleanField(default=True, verbose_name='پابلیش لینک کتاب'),
        ),
        migrations.AlterField(
            model_name='books',
            name='bookname',
            field=models.CharField(max_length=1000, verbose_name='نام فایل کتاب'),
        ),
        migrations.AlterField(
            model_name='books',
            name='coursenamefkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tutorialbook.coursebook2', verbose_name='نام کتاب'),
        ),
        migrations.AlterField(
            model_name='coursebook2',
            name='coursename',
            field=models.CharField(max_length=1000, verbose_name='نام کتاب'),
        ),
        migrations.AlterField(
            model_name='coursebook2',
            name='hazine',
            field=models.IntegerField(verbose_name='هزینه به ریال'),
        ),
        migrations.AlterField(
            model_name='coursebook2',
            name='maghtafkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.maghtaTahsili', verbose_name='مقطع'),
        ),
        migrations.AlterField(
            model_name='coursebook2',
            name='modaresinfkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.modaresin', verbose_name='نام نویسنده'),
        ),
        migrations.AlterField(
            model_name='coursebook2',
            name='pic',
            field=models.ImageField(upload_to='coursebook/photos/%y/%m/%d/', verbose_name='فایل عکس'),
        ),
        migrations.AlterField(
            model_name='coursebook2',
            name='reshteTahsilifkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.reshteTahsili', verbose_name='رشته'),
        ),
        migrations.AlterField(
            model_name='coursebook2',
            name='saattadris',
            field=models.CharField(max_length=1000, verbose_name='زمان درس'),
        ),
        migrations.AlterField(
            model_name='coursebook2',
            name='tozihat',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='tutorialbookadmin',
            name='pic',
            field=models.ImageField(upload_to='tutorialbook/photos/%y/%m/%d/', verbose_name='عکس بالای صفحه'),
        ),
        migrations.AlterField(
            model_name='tutorialbookadmin',
            name='text_click',
            field=models.CharField(max_length=500, verbose_name='تیتر دکمه سرچ'),
        ),
        migrations.AlterField(
            model_name='tutorialbookadmin',
            name='title_1',
            field=models.CharField(max_length=500, verbose_name='تیتر اول، فایل های پیشنهادی'),
        ),
        migrations.AlterField(
            model_name='tutorialbookadmin',
            name='title_2',
            field=models.CharField(max_length=500, verbose_name='تیتر دوم، جدیدترین فایل ها'),
        ),
        migrations.AlterField(
            model_name='tutorialbookadmin',
            name='title_page',
            field=models.CharField(max_length=500, verbose_name='تیتر صفحه'),
        ),
        migrations.AlterField(
            model_name='tutorialbookadmin',
            name='title_search',
            field=models.CharField(max_length=500, verbose_name='تیتر قسمت سرچ'),
        ),
    ]
