# Generated by Django 3.0.2 on 2020-09-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialbook', '0004_auto_20200713_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursebook2',
            name='hazine',
            field=models.IntegerField(verbose_name='هزینه به تومان'),
        ),
    ]
