# Generated by Django 3.0.2 on 2020-09-10 19:28

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialbook', '0005_auto_20200910_2102'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursebook2',
            name='tozihat',
            field=ckeditor.fields.RichTextField(verbose_name='توضیحات'),
        ),
    ]
