# Generated by Django 3.0.2 on 2020-11-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialbook', '0006_auto_20200910_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorialbookadmin',
            name='icon',
            field=models.ImageField(default=1, upload_to='tutorialbook/photos/%y/%m/%d/', verbose_name='عکس آیکون'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='coursebook2',
            name='saattadris',
            field=models.CharField(max_length=1000, verbose_name='تعداد صفحات'),
        ),
    ]
