# Generated by Django 3.0.2 on 2020-11-08 19:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialbook', '0007_auto_20201107_2152'),
    ]

    operations = [
        migrations.CreateModel(
            name='bookpics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bookpicname', models.CharField(max_length=1000, verbose_name='نام عکس')),
                ('bookpiclink_is_published', models.BooleanField(default=True, verbose_name='پابلیش لینک عکس')),
                ('bookpiclink', models.CharField(blank=True, max_length=1000, verbose_name='لینک عکس')),
                ('bookpicfile_is_published', models.BooleanField(default=True, verbose_name='پابلیش فایل عکس')),
                ('bookpicfile', models.FileField(blank=True, upload_to='coursebook/books/%y/%m/%d/', verbose_name='فایل عکس')),
                ('coursenamefkey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tutorialbook.coursebook2', verbose_name='نام درس')),
            ],
            options={
                'verbose_name_plural': 'عکس های محصول',
            },
        ),
    ]
