# Generated by Django 3.0.2 on 2020-11-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialbook', '0008_bookpics'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursebook2',
            name='hazineoff',
            field=models.IntegerField(default=1, verbose_name='هزینه با تخفیف به تومان'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursebook2',
            name='off_is_published',
            field=models.BooleanField(default=True, verbose_name='تخفیف دارد'),
        ),
    ]
