# Generated by Django 3.0.2 on 2020-03-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='footerAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=2000)),
                ('twitter', models.CharField(max_length=2000)),
                ('twitter_published', models.BooleanField(default=True)),
                ('linkedin', models.CharField(max_length=2000)),
                ('linkedin_published', models.BooleanField(default=True)),
                ('instagram', models.CharField(max_length=2000)),
                ('instagram_published', models.BooleanField(default=True)),
                ('mail', models.CharField(max_length=2000)),
                ('mail_published', models.BooleanField(default=True)),
                ('whatsapp', models.CharField(max_length=2000)),
                ('whatsapp_published', models.BooleanField(default=True)),
                ('telegram', models.CharField(max_length=2000)),
                ('telegram_published', models.BooleanField(default=True)),
            ],
        ),
    ]
