# Generated by Django 3.0.2 on 2020-03-24 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ostanha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ostanName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='shahrha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shahrNames', models.CharField(max_length=100)),
                ('ostanNamefkey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.ostanha')),
            ],
        ),
    ]
