# Generated by Django 3.0.2 on 2020-03-26 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_ostanha_shahrha'),
    ]

    operations = [
        migrations.CreateModel(
            name='maghtaTahsili',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maghta', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='reshteTahsili',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reshte', models.CharField(max_length=100)),
                ('maghtafkey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.maghtaTahsili')),
            ],
        ),
    ]
