# Generated by Django 3.0.2 on 2020-04-03 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_maghtatahsili_reshtetahsili'),
    ]

    operations = [
        migrations.CreateModel(
            name='modaresin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modares', models.CharField(max_length=300)),
                ('email_modares', models.CharField(max_length=2000)),
            ],
        ),
    ]
