# Generated by Django 3.0.2 on 2020-06-01 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_modaresin'),
    ]

    operations = [
        migrations.CreateModel(
            name='sliderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='slider/photos/%y/%m/%d/')),
            ],
        ),
    ]
