# Generated by Django 3.0.2 on 2020-08-29 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0007_advertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footeradmin',
            name='whatsapp',
            field=models.CharField(max_length=2000, verbose_name='شماره واتس اپ'),
        ),
    ]
