# Generated by Django 3.0.2 on 2020-10-15 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0008_auto_20200829_1525'),
    ]

    operations = [
        migrations.CreateModel(
            name='pagecunter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.IntegerField(verbose_name='تعداد بازدید کننده')),
            ],
            options={
                'verbose_name_plural': 'تعداد بازدید',
            },
        ),
    ]
