# Generated by Django 3.0.2 on 2020-10-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0009_pagecunter'),
    ]

    operations = [
        migrations.AddField(
            model_name='maghtatahsili',
            name='logo',
            field=models.CharField(default=1, max_length=100, verbose_name='لوگوی مقطع تحصیلی'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reshtetahsili',
            name='logo',
            field=models.CharField(default=1, max_length=100, verbose_name='لوگوی رشته تحصیلی'),
            preserve_default=False,
        ),
    ]
