# Generated by Django 3.0.2 on 2020-03-19 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_page', models.CharField(max_length=200)),
                ('pic', models.ImageField(upload_to='photos/%y/%m/%d/')),
                ('title_message', models.CharField(max_length=200)),
                ('click', models.CharField(max_length=30)),
                ('address', models.TextField(blank=True)),
            ],
        ),
    ]
