# Generated by Django 3.0.2 on 2020-03-30 14:53

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0003_contactuserpayam'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contactuserpayam',
            new_name='contactuserpayam1',
        ),
    ]
