# Generated by Django 3.0.2 on 2020-03-30 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_contactuserpayam4'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactuserpayam1',
        ),
    ]
