# Generated by Django 3.0.2 on 2020-03-30 15:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0006_delete_contactuserpayam1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactuserpayam4',
            name='tarikhjavab',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
