# Generated by Django 3.0.2 on 2020-03-30 15:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0007_auto_20200330_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactuserpayam4',
            name='tarikhjavab',
            field=models.DateTimeField(blank=True, default=datetime.date(2020, 3, 30)),
        ),
    ]
