# Generated by Django 3.0.2 on 2020-03-30 15:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_karbaruser'),
        ('contact', '0009_auto_20200330_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactuserpayam4',
            name='tarikhjavab',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2020, 3, 30, 20, 11, 30, 633626)),
        ),
        migrations.AlterField(
            model_name='contactuserpayam4',
            name='usernamefkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.karbaruser1'),
        ),
    ]
