# Generated by Django 3.0.2 on 2020-03-30 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0013_auto_20200330_2013'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactuserpayam4',
            name='tarikhjavab',
        ),
    ]
