# Generated by Django 3.0.2 on 2020-07-13 08:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contact', '0016_contactuserpm'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactadmin',
            options={'verbose_name_plural': 'تنظیمات صفحه تماس با ما'},
        ),
        migrations.AlterModelOptions(
            name='contactuserpayam4',
            options={'verbose_name_plural': 'سوالات کاربران و جواب دهی'},
        ),
        migrations.AlterModelOptions(
            name='contactuserpm',
            options={'verbose_name_plural': 'سوالات کاربران و جواب دهی'},
        ),
        migrations.AlterField(
            model_name='contactadmin',
            name='address',
            field=models.TextField(blank=True, verbose_name='آدرس نقشه گوگل'),
        ),
        migrations.AlterField(
            model_name='contactadmin',
            name='click',
            field=models.CharField(max_length=30, verbose_name='تیتر کلیک'),
        ),
        migrations.AlterField(
            model_name='contactadmin',
            name='pic',
            field=models.ImageField(upload_to='contact/photos/%y/%m/%d/', verbose_name='عکس بالای صفحه'),
        ),
        migrations.AlterField(
            model_name='contactadmin',
            name='title_message',
            field=models.CharField(max_length=200, verbose_name='تیتر قسمت ارسال پیام'),
        ),
        migrations.AlterField(
            model_name='contactadmin',
            name='title_page',
            field=models.CharField(max_length=200, verbose_name='تیتر صفحه'),
        ),
        migrations.AlterField(
            model_name='contactuserpayam4',
            name='javabadmin',
            field=models.TextField(blank=True, verbose_name='جواب ادمین'),
        ),
        migrations.AlterField(
            model_name='contactuserpayam4',
            name='soal',
            field=models.TextField(blank=True, verbose_name='سوال کاربر'),
        ),
        migrations.AlterField(
            model_name='contactuserpayam4',
            name='usernamefkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='تیتر صفحه'),
        ),
        migrations.AlterField(
            model_name='contactuserpm',
            name='javabadmin',
            field=models.TextField(blank=True, verbose_name='جواب ادمین'),
        ),
        migrations.AlterField(
            model_name='contactuserpm',
            name='soal',
            field=models.TextField(blank=True, verbose_name='سوال کاربر'),
        ),
        migrations.AlterField(
            model_name='contactuserpm',
            name='usernamefkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='کاربر مورد نظر'),
        ),
    ]
