# Generated by Django 3.0.2 on 2020-03-29 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_karbaruser1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='karbaruser',
        ),
    ]
