# Generated by Django 3.0.2 on 2020-07-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_karbaruser'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='karbaruser1',
            options={'verbose_name_plural': 'تنظیمات کاربران'},
        ),
        migrations.AlterField(
            model_name='karbaruser1',
            name='email',
            field=models.EmailField(max_length=200, verbose_name='ایمیل'),
        ),
        migrations.AlterField(
            model_name='karbaruser1',
            name='first_name',
            field=models.CharField(max_length=200, verbose_name='نام'),
        ),
        migrations.AlterField(
            model_name='karbaruser1',
            name='gender',
            field=models.CharField(max_length=200, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='karbaruser1',
            name='last_name',
            field=models.CharField(max_length=200, verbose_name='نام خانوادگی'),
        ),
        migrations.AlterField(
            model_name='karbaruser1',
            name='maghta',
            field=models.CharField(max_length=200, verbose_name='مقطع تحصیلی'),
        ),
        migrations.AlterField(
            model_name='karbaruser1',
            name='melli_code',
            field=models.IntegerField(verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='karbaruser1',
            name='ostan',
            field=models.CharField(max_length=200, verbose_name='استان'),
        ),
        migrations.AlterField(
            model_name='karbaruser1',
            name='password',
            field=models.CharField(max_length=200, verbose_name='پسورد'),
        ),
        migrations.AlterField(
            model_name='karbaruser1',
            name='reshte',
            field=models.CharField(max_length=200, verbose_name='رشته تحصیلی'),
        ),
        migrations.AlterField(
            model_name='karbaruser1',
            name='shahr',
            field=models.CharField(max_length=200, verbose_name='شهر'),
        ),
        migrations.AlterField(
            model_name='karbaruser1',
            name='tell',
            field=models.IntegerField(verbose_name='موبایل'),
        ),
        migrations.AlterField(
            model_name='karbaruser1',
            name='username',
            field=models.CharField(max_length=200, verbose_name='نام کاربری'),
        ),
    ]
