# Generated by Django 3.0.2 on 2020-08-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20200713_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='karbaruser1',
            name='melli_code',
            field=models.CharField(max_length=200, verbose_name='کد ملی'),
        ),
        migrations.AlterField(
            model_name='karbaruser1',
            name='tell',
            field=models.CharField(max_length=200, verbose_name='موبایل'),
        ),
    ]
