# Generated by Django 3.0.2 on 2020-04-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='tutorialvideoAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_page', models.CharField(max_length=500)),
                ('pic', models.ImageField(upload_to='tutorialvideo/photos/%y/%m/%d/')),
                ('title_search', models.CharField(max_length=500)),
                ('text_click', models.CharField(max_length=500)),
                ('title_1', models.CharField(max_length=500)),
                ('title_2', models.CharField(max_length=500)),
            ],
        ),
    ]
