# Generated by Django 3.0.2 on 2020-04-03 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_modaresin'),
        ('tutorialvideo', '0002_coursevideo1'),
    ]

    operations = [
        migrations.CreateModel(
            name='coursevideo2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic', models.ImageField(upload_to='coursevideo/photos/%y/%m/%d/')),
                ('coursename', models.CharField(max_length=1000)),
                ('saattadris', models.CharField(max_length=1000)),
                ('tozihat', models.TextField()),
                ('hazine', models.IntegerField()),
                ('maghtafkey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.maghtaTahsili')),
                ('modaresinfkey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.modaresin')),
                ('reshteTahsilifkey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.reshteTahsili')),
            ],
        ),
        migrations.DeleteModel(
            name='coursevideo1',
        ),
    ]
