# Generated by Django 3.0.2 on 2020-04-09 12:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialvideo', '0003_auto_20200403_1740'),
    ]

    operations = [
        migrations.CreateModel(
            name='videos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videoname', models.CharField(max_length=1000)),
                ('videolink_is_published', models.BooleanField(default=True)),
                ('videolink', models.CharField(max_length=1000)),
                ('videofile_is_published', models.BooleanField(default=True)),
                ('videofile', models.FileField(upload_to='coursevideo/videos/%y/%m/%d/')),
                ('coursenamefkey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tutorialvideo.coursevideo2')),
            ],
        ),
    ]
