# Generated by Django 3.0.2 on 2020-05-24 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialvideo', '0004_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='videofile',
            field=models.FileField(blank=True, upload_to='coursevideo/videos/%y/%m/%d/'),
        ),
    ]
