# Generated by Django 3.0.2 on 2020-07-13 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_auto_20200713_1241'),
        ('tutorialvideo', '0006_auto_20200524_1852'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coursevideo2',
            options={'verbose_name_plural': 'درس ها'},
        ),
        migrations.AlterModelOptions(
            name='tutorialvideoadmin',
            options={'verbose_name_plural': 'تنظیمات صفحه'},
        ),
        migrations.AlterModelOptions(
            name='videos',
            options={'verbose_name_plural': 'ویدیو ها'},
        ),
        migrations.AlterField(
            model_name='coursevideo2',
            name='coursename',
            field=models.CharField(max_length=1000, verbose_name='نام درس'),
        ),
        migrations.AlterField(
            model_name='coursevideo2',
            name='hazine',
            field=models.IntegerField(verbose_name='هزینه به ریال'),
        ),
        migrations.AlterField(
            model_name='coursevideo2',
            name='maghtafkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.maghtaTahsili', verbose_name='مقطع'),
        ),
        migrations.AlterField(
            model_name='coursevideo2',
            name='modaresinfkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.modaresin', verbose_name='نام استاد'),
        ),
        migrations.AlterField(
            model_name='coursevideo2',
            name='pic',
            field=models.ImageField(upload_to='coursevideo/photos/%y/%m/%d/', verbose_name='فایل عکس'),
        ),
        migrations.AlterField(
            model_name='coursevideo2',
            name='reshteTahsilifkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='pages.reshteTahsili', verbose_name='رشته'),
        ),
        migrations.AlterField(
            model_name='coursevideo2',
            name='saattadris',
            field=models.CharField(max_length=1000, verbose_name='زمان درس'),
        ),
        migrations.AlterField(
            model_name='coursevideo2',
            name='tozihat',
            field=models.TextField(verbose_name='توضیحات'),
        ),
        migrations.AlterField(
            model_name='tutorialvideoadmin',
            name='pic',
            field=models.ImageField(upload_to='tutorialvideo/photos/%y/%m/%d/', verbose_name='عکس بالای صفحه'),
        ),
        migrations.AlterField(
            model_name='tutorialvideoadmin',
            name='text_click',
            field=models.CharField(max_length=500, verbose_name='تیتر دکمه سرچ'),
        ),
        migrations.AlterField(
            model_name='tutorialvideoadmin',
            name='title_1',
            field=models.CharField(max_length=500, verbose_name='تیتر اول، ویدیوهای پیشنهادی'),
        ),
        migrations.AlterField(
            model_name='tutorialvideoadmin',
            name='title_2',
            field=models.CharField(max_length=500, verbose_name='تیتر دوم، جدیدترین ویدیوها'),
        ),
        migrations.AlterField(
            model_name='tutorialvideoadmin',
            name='title_page',
            field=models.CharField(max_length=500, verbose_name='تیتر صفحه'),
        ),
        migrations.AlterField(
            model_name='tutorialvideoadmin',
            name='title_search',
            field=models.CharField(max_length=500, verbose_name='تیتر قسمت سرچ'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='coursenamefkey',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tutorialvideo.coursevideo2', verbose_name='نام درس'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='videofile',
            field=models.FileField(blank=True, upload_to='coursevideo/videos/%y/%m/%d/', verbose_name='فایل ویدیو'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='videofile_is_published',
            field=models.BooleanField(default=True, verbose_name='پابلیش فایل ویدیو'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='videolink',
            field=models.CharField(blank=True, max_length=1000, verbose_name='لینک ویدیو'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='videolink_is_published',
            field=models.BooleanField(default=True, verbose_name='پابلیش لینک ویدیو'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='videoname',
            field=models.CharField(max_length=1000, verbose_name='نام ویدیو'),
        ),
    ]
