# Generated by Django 3.0.2 on 2020-10-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialvideo', '0009_auto_20200910_2358'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursevideo2',
            name='tizer',
            field=models.CharField(default=1, max_length=1000, verbose_name='نام درس'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='coursevideo2',
            name='tizer_is_published',
            field=models.BooleanField(default=True, verbose_name='پابلیش فایل ویدیو'),
        ),
    ]
