# Generated by Django 3.0.2 on 2020-10-23 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialvideo', '0010_auto_20201019_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursevideo2',
            name='tizer',
            field=models.CharField(max_length=1000, verbose_name='لینک فایل تیزر'),
        ),
        migrations.AlterField(
            model_name='coursevideo2',
            name='tizer_is_published',
            field=models.BooleanField(default=True, verbose_name='نمایش فایل تیزر'),
        ),
    ]
