# Generated by Django 3.0.2 on 2020-11-07 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialvideo', '0011_auto_20201023_1257'),
    ]

    operations = [
        migrations.CreateModel(
            name='videopics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('videopicname', models.CharField(max_length=1000, verbose_name='نام عکس')),
                ('videopiclink_is_published', models.BooleanField(default=True, verbose_name='پابلیش لینک عکس')),
                ('videopiclink', models.CharField(blank=True, max_length=1000, verbose_name='لینک عکس')),
                ('videopicfile_is_published', models.BooleanField(default=True, verbose_name='پابلیش فایل عکس')),
                ('videopicfile', models.FileField(blank=True, upload_to='coursevideo/videos/%y/%m/%d/', verbose_name='فایل عکس')),
                ('coursenamefkey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tutorialvideo.coursevideo2', verbose_name='نام درس')),
            ],
            options={
                'verbose_name_plural': 'عکس های محصول',
            },
        ),
    ]
