# Generated by Django 3.0.2 on 2021-01-16 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20201023_1257'),
        ('tutorialvideo', '0014_coursevideo2_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursevideo2',
            name='maghtafkey',
        ),
        migrations.AddField(
            model_name='coursevideo2',
            name='maghtafkey',
            field=models.ManyToManyField(to='pages.maghtaTahsili', verbose_name='مقطع'),
        ),
    ]
