# Generated by Django 3.0.2 on 2021-01-16 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20201023_1257'),
        ('tutorialvideo', '0015_auto_20210116_1532'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursevideo2',
            name='reshteTahsilifkey',
        ),
        migrations.AddField(
            model_name='coursevideo2',
            name='reshteTahsilifkey',
            field=models.ManyToManyField(to='pages.reshteTahsili', verbose_name='رشته'),
        ),
    ]
