# Generated by Django 3.0.2 on 2021-01-16 12:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0010_auto_20201023_1257'),
        ('tutorialvideo', '0016_auto_20210116_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coursevideo2',
            name='maghtafkey',
        ),
        migrations.AddField(
            model_name='coursevideo2',
            name='maghtafkey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.maghtaTahsili', verbose_name='مقطع'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='coursevideo2',
            name='reshteTahsilifkey',
        ),
        migrations.AddField(
            model_name='coursevideo2',
            name='reshteTahsilifkey',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='pages.reshteTahsili', verbose_name='رشته'),
            preserve_default=False,
        ),
    ]
