# Generated by Django 3.0.2 on 2020-08-29 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='buys',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.IntegerField(verbose_name='آیدی کاربر')),
                ('username', models.CharField(max_length=5000, verbose_name='نام کاربری')),
                ('address', models.CharField(max_length=5000, verbose_name='آدرس')),
                ('email', models.CharField(max_length=5000, verbose_name='ایمیل')),
                ('mobile', models.CharField(max_length=5000, verbose_name='موبایل')),
                ('coursetype', models.CharField(max_length=5000, verbose_name='نوع درس')),
                ('courseid', models.IntegerField(verbose_name='آیدی درس')),
                ('coursename', models.CharField(max_length=5000, verbose_name='نام درس')),
                ('description', models.CharField(max_length=5000, verbose_name='توضیحات فروش ')),
                ('amount', models.CharField(max_length=5000, verbose_name='هزینه')),
            ],
            options={
                'verbose_name_plural': 'خرید ها',
            },
        ),
    ]
