# Generated by Django 3.0.2 on 2020-09-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zarinpal', '0002_auto_20200830_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buys',
            name='amount',
            field=models.CharField(max_length=5000, verbose_name='هزینه به تومان'),
        ),
    ]
