# Generated by Django 3.0.2 on 2020-08-11 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classlinks', '0002_allclasslinks1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='allclasslinks1',
            name='link_date',
            field=models.DateField(verbose_name='تاریخ برگزاری کلاس'),
        ),
    ]
