# Generated by Django 3.0.2 on 2020-07-13 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alllinks',
            options={'verbose_name_plural': 'لینک ها'},
        ),
        migrations.AlterModelOptions(
            name='linksadmin',
            options={'verbose_name_plural': 'تنظیمات صفحه لینک های مفید'},
        ),
        migrations.AlterField(
            model_name='alllinks',
            name='link_title',
            field=models.CharField(max_length=3000, verbose_name='تیتر لینک'),
        ),
        migrations.AlterField(
            model_name='alllinks',
            name='link_url',
            field=models.CharField(max_length=3000, verbose_name='آدرس لینک '),
        ),
        migrations.AlterField(
            model_name='linksadmin',
            name='pic',
            field=models.ImageField(upload_to='links/photos/%y/%m/%d/', verbose_name='عکس بالای صفحه'),
        ),
        migrations.AlterField(
            model_name='linksadmin',
            name='title_links',
            field=models.CharField(max_length=500, verbose_name='تیتر لینک ها'),
        ),
        migrations.AlterField(
            model_name='linksadmin',
            name='title_page',
            field=models.CharField(max_length=500, verbose_name='تیتر صفحه'),
        ),
    ]
