# Generated by Django 3.0.2 on 2020-09-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialapplication', '0002_auto_20200713_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseapplication2',
            name='hazine',
            field=models.IntegerField(verbose_name='هزینه به تومان'),
        ),
    ]
