# Generated by Django 3.0.2 on 2020-11-08 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialapplication', '0004_auto_20200910_2358'),
    ]

    operations = [
        migrations.CreateModel(
            name='applicationpics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('applicationpicname', models.CharField(max_length=1000, verbose_name='نام عکس')),
                ('applicationpiclink_is_published', models.BooleanField(default=True, verbose_name='پابلیش لینک عکس')),
                ('applicationpiclink', models.CharField(blank=True, max_length=1000, verbose_name='لینک عکس')),
                ('applicationpicfile_is_published', models.BooleanField(default=True, verbose_name='پابلیش فایل عکس')),
                ('applicationpicfile', models.FileField(blank=True, upload_to='courseapplication/applications/%y/%m/%d/', verbose_name='فایل عکس')),
                ('coursenamefkey', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='tutorialapplication.courseapplication2', verbose_name='نام درس')),
            ],
            options={
                'verbose_name_plural': 'عکس های محصول',
            },
        ),
    ]
