# Generated by Django 3.0.2 on 2020-11-12 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutorialapplication', '0006_auto_20201111_2051'),
    ]

    operations = [
        migrations.AddField(
            model_name='courseapplication2',
            name='size',
            field=models.CharField(default=100, max_length=1000, verbose_name='حجم فایل به مگابایت'),
            preserve_default=False,
        ),
    ]
